version: '3'
services:
  dev-container:
    image: mirrors.tencent.com/red/workspace:latest
    container_name: workspace
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${VOLUME}:/root/${VOLUME}"
      - "/root/.vscode-server/:/root/.vscode-server/"
    entrypoint:
      - /usr/sbin/sshd
      - -D
    privileged: true
    network_mode: "host"
