version: '3'
services:
  dev-container:
    image: kevinlin86/dev-container
    container_name: dev
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${VOLUME}:/root/${VOLUME}"
      - "/root/.vscode-server/:/root/.vscode-server/"
    entrypoint:
      - /usr/sbin/sshd
      - -D
    privileged: true
    ports:
      - "7822:22/tcp"