version: '3'
services:
  dev-container:
    image: mirrors.tencent.com/red/workspace:latest
    container_name: workspace
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${VOLUME}:/root/${VOLUME}"
      - "/root/.vscode-server/:/root/.vscode-server/"
    entrypoint:
      - tail
      - -f
      - /dev/null
    ports:
      - "${ADDR:-127.0.0.1:1234}:22"
    privileged: true
    network_mode: "host"
