version: '3'
services:
  workspace:
    image: mirrors.tencent.com/red/workspace:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "/:/rootfs"
      - "/root/.vscode-server/:/root/.vscode-server/"
    privileged: true
    network_mode: "host"
