name: Docker Image CI

on:
  push:
    branches: [ "master", "tag/*", "action"]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: kevinlin86/dev-container
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: DOCKER_HUB
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PWD }} 
      #&& docker push ${IMAGE_NAME}:${GITHUB_REF_NAME}

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile.github --tag ${IMAGE_NAME}:${GITHUB_REF_NAME}
    # - name: Deploy to docker hub
      # run: docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PWD}} && docker push ${IMAGE_NAME}:${GITHUB_REF_NAME}
      
