name: Docker Image CI

on:
  push:
    branches: [ "master"]
    tags: ["*"]

env:
  IMAGE_NAME: kevinlin86/dev-container
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: DOCKER_HUB
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.github --tag ${IMAGE_NAME}:${GITHUB_REF_NAME}
    - name: Deploy to docker hub
      run: |
        echo ${{ secrets.DOCKER_HUB_PWD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin 
        TAG=${GITHUB_REF_NAME}
        if [ $GITHUB_REF_NAME == "master" ]; then 
          TAG="latest"
          docker tag ${IMAGE_NAME}:${GITHUB_REF_NAME} ${IMAGE_NAME}:latest
        fi
        
        docker push ${IMAGE_NAME}:${TAG}